seasons = {
    1: {
        1: "Cartman Gets an Anal Probe",
        2: "Weight Gain 4000",
        3: "Volcano",
        4: "Big Gay Al's Big Gay Boat Ride",
        5: "An Elephant Makes Love to a Pig",
        6: "Death",
        7: "Pinkeye",
        8: "Starvin' Marvin",
        9: "Mr. Hankey, the Christmas Poo",
        10: "Damien",
        11: "Tom's Rhinoplasty",
        12: "Mecha-Streisand",
        13: "Cartman's Mom Is a Dirty Slut"
    },
    2: {
        1: "Terrance and Phillip in Not Without My Anus",
        2: "Cartman's Mom Is Still a Dirty Slut",
        3: "Ike's Wee Wee",
        4: "Chickenlover",
        5: "Conjoined Fetus Lady",
        6: "The Mexican Staring Frog of Southern Sri Lanka",
        7: "City on the Edge of Forever Flashbacks",
        8: "Summer Sucks",
        9: "Chef's Chocolate Salty Balls",
        10: "Chickenpox",
        11: "Roger Ebert Should Lay Off the Fatty Foods",
        12: "Clubhouses",
        13: "Cow Days",
        14: "Chef Aid",
        15: "Spookyfish",
        16: "Merry Christmas, Charlie Manson!",
        17: "Gnomes",
        18: "Prehistoric Ice Man"
    },
    3: {
        1: "Rainforest Shmainforest",
        2: "Spontaneous Combustion",
        3: "Succubus",
        4: "Jakovasaurs",
        5: "Tweek vs. Craig",
        6: "Sexual Harassment Panda",
        7: "Cat Orgy",
        8: "Two Guys Naked in a Hot Tub",
        9: "Jewbilee",
        10: "Korn's Groovy Pirate Ghost Mystery",
        11: "Chinpokomon",
        12: "Hooked on Monkey Fonics",
        13: "Starvin' Marvin in Space",
        14: "The Red Badge of Gayness",
        15: "Mr. Hankey's Christmas Classics",
        16: "Are You There God? It's Me, Jesus",
        17: "World Wide Recorder Concert"
    },
    4: {
        1: "The Tooth Fairy's Tats 2000",
        2: "Cartman's Silly Hate Crime 2000",
        3: "Timmy 2000",
        4: "Quintuplets 2000",
        5: "Cartman Joins NAMBLA",
        6: "Cherokee Hair Tampons",
        7: "Chef Goes Nanners",
        8: "Something You Can Do with Your Finger",
        9: "Do the Handicapped Go to Hell?",
        10: "Probably",
        11: "4th Grade",
        12: "Trapper Keeper",
        13: "Helen Keller! The Musical",
        14: '"Pip"Great Expectations',
        15: "Fat Camp",
        16: "The Wacky Molestation Adventure",
        17: "A Very Crappy Christmas"
    },
    5: {
        1: "It Hits the Fan",
        2: "Cripple Fight",
        3: "Super Best Friends",
        4: "Scott Tenorman Must Die",
        5: "Terrance and Phillip: Behind the Blow",
        6: "Cartmanland",
        7: "Proper Condom Use",
        8: "Towelie",
        9: "Osama bin Laden Has Farty Pants",
        10: "How to Eat with Your Butt",
        11: "The Entity",
        12: "Here Comes the Neighborhood",
        13: "Kenny Dies",
        14: "Butters' Very Own Episode"
    },
    6: {
        1: "Jared Has Aides",
        2: "Asspen",
        3: "Freak Strike",
        4: "Fun with Veal",
        5: "The New Terrance and Phillip Movie Trailer",
        6: "Professor Chaos",
        7: "Simpsons Already Did It",
        8: "Red Hot Catholic Love",
        9: "Free Hat",
        10: "Bebe's Boobs Destroy Society",
        11: "Child Abduction Is Not Funny",
        12: "A Ladder to Heaven",
        13: "The Return of the Fellowship of the Ring to the Two Towers",
        14: "The Death Camp of Tolerance",
        15: "The Biggest Douche in the Universe",
        16: "My Future Self 'n' Me",
        17: "Red Sleigh Down"
    },
    7: {
        1: "Cancelled",
        2: "Krazy Kripples",
        3: "Toilet Paper",
        4: "I'm a Little Bit Country",
        5: "Fat Butt and Pancake Head",
        6: "Lil' Crime Stoppers",
        7: "Red Man's Greed",
        8: "South Park Is Gay",
        9: "Christian Rock Hard",
        10: "Grey Dawn",
        11: "Casa Bonita",
        12: "All About Mormons",
        13: "Butt Out",
        14: "Raisins",
        15: "It's Christmas in Canada"
    },
    8: {
        1: "Good Times with Weapons",
        2: "Up the Down Steroid",
        3: "The Passion of the Jew",
        4: "You Got F'd in the A",
        5: "Awesom-O",
        6: "The Jeffersons",
        7: "Goobacks",
        8: "Douche and Turd",
        9: "Something Wall-Mart This Way Comes",
        10: "Pre-School",
        11: "Quest for Ratings",
        12: "Stupid Spoiled Whore Video Playset",
        13: "Cartman's Incredible Gift",
        14: "Woodland Critter Christmas"
    },
    9: {
        1: "Mr. Garrison's Fancy New Vagina",
        2: "Die Hippie, Die",
        3: "Wing",
        4: "Best Friends Forever",
        5: "The Losing Edge",
        6: "The Death of Eric Cartman",
        7: "Erection Day",
        8: "Two Days Before the Day After Tomorrow",
        9: "Marjorine",
        10: "Follow That Egg!",
        11: "Ginger Kids",
        12: "Trapped in the Closet",
        13: "Free Willzyx",
        14: "Bloody Mary"
    },
    10: {
        1: "The Return of Chef",
        2: "Smug Alert!",
        3: "Cartoon Wars Part I",
        4: "Cartoon Wars Part II",
        5: "A Million Little Fibers",
        6: "ManBearPig",
        7: "Tsst",
        8: "Make Love, Not Warcraft",
        9: "Mystery of the Urinal Deuce",
        10: "Miss Teacher Bangs a Boy",
        11: "Hell on Earth 2006",
        12: "Go God Go",
        13: "Go God Go XII",
        14: "Stanley's Cup"
    },
    11: {
        1: "With Apologies to Jesse Jackson",
        2: "Cartman Sucks",
        3: "Lice Capades",
        4: "The Snuke",
        5: "Fantastic Easter Special",
        6: "D-Yikes!",
        7: "Night of the Living Homeless",
        8: "Le Petit Tourette",
        9: "More Crap",
        10: "Imaginationland Episode I",
        11: "Imaginationland Episode II",
        12: "Imaginationland Episode III",
        13: "Guitar Queer-O",
        14: "The List"
    },
    12: {
        1: "Tonsil Trouble",
        2: "Britney's New Look",
        3: "Major Boobage",
        4: "Canada on Strike",
        5: "Eek, a Penis!",
        6: "Over Logging",
        7: "Super Fun Time",
        8: "The China Probrem",
        9: "Breast Cancer Show Ever",
        10: "Pandemic",
        11: "Pandemic 2: The Startling",
        12: "About Last Night...",
        13: "Elementary School Musical",
        14: "The Ungroundable"
    },
    13: {
        1: "The Ring",
        2: "The Coon",
        3: "Margaritaville",
        4: "Eat, Pray, Queef",
        5: "Fishsticks",
        6: "Pinewood Derby",
        7: "Fatbeard",
        8: "Dead Celebrities",
        9: "Butters' Bottom Bitch",
        10: "W.T.F.",
        11: "Whale Whores",
        12: "The F Word",
        13: "Dances with Smurfs",
        14: "Pee"
    },
    14: {
        1: "Sexual Healing",
        2: "The Tale of Scrotie McBoogerballs",
        3: "Medicinal Fried Chicken",
        4: "You Have 0 Friends",
        5: "200",
        6: "201",
        7: "Crippled Summer",
        8: "Poor and Stupid",
        9: "It's a Jersey Thing",
        10: "Insheeption",
        11: "Coon 2: Hindsight",
        12: "Mysterion Rises",
        13: "Coon vs. Coon and Friends",
        14: "Crème Fraîche"
    },
    15: {
        1: "HumancentiPad",
        2: "Funnybot",
        3: "Royal Pudding",
        4: "T.M.I.",
        5: 	"Crack Baby Athletic Association",
        6: "City Sushi",
        7: "You're Getting Old",
        8: "Ass Burgers",
        9: "The Last of the Meheecans",
        10: "Bass to Mouth",
        11: "Broadway Bro Down",
        12: "1%",
        13: "A History Channel Thanksgiving",
        14: "The Poor Kid"
    },
    16: {
        1: "Reverse Cowgirl",
        2: "Cash for Gold",
        3: "Faith Hilling",
        4: "Jewpacabra",
        5: "Butterballs",
        6: "I Should Have Never Gone Ziplining",
        7: "Cartman Finds Love",
        8: "Sarcastaball",
        9: "Raising the Bar",
        10: "Insecurity",
        11: "Going Native",
        12: "A Nightmare on FaceTime",
        13: "A Scause for Applause",
        14: "Obama Wins!"
    },
    17: {
        1: "Let Go, Let Gov",
        2: "Informative Murder Porn",
        3: "World War Zimmerman",
        4: "Goth Kids 3: Dawn of the Posers",
        5: "Taming Strange",
        6: "Ginger Cow",
        7: "Black Friday",
        8: "A Song of Ass and Fire",
        9: "Titties and Dragons",
        10: "The Hobbit"
    },
    18: {
        1: "Go Fund Yourself",
        2: "Gluten Free Ebola",
        3: "The Cissy",
        4: "Handicar",
        5: "The Magic Bush",
        6: "Freemium Isn't Free",
        7: "Grounded Vindaloop",
        8: "Cock Magic",
        9: "#REHASH",
        10: "#HappyHolograms"
    },
    19: {
        1: "Stunning and Brave",
        2: "Where My Country Gone?",
        3: "The City Part of Town",
        4: "You're Not Yelping",
        5: "Safe Space",
        6: "Tweek x Craig",
        7: "Naughty Ninjas",
        8: "Sponsored Content",
        9: "Truth and Advertising",
        10: "PC Principal Final Justice"
    },
    20: {
        1: "Member Berries",
        2: "Skank Hunt",
        3: "The Damned",
        4: "Wieners Out",
        5: "Douche and a Danish",
        6: "Fort Collins",
        7: 	"Oh, Jeez",
        8: "Members Only",
        9: "Not Funny",
        10: "The End of Serialization as We Know It"
    },
    21: {
        1: "White People Renovating Houses",
        2: "Put It Down",
        3: "Holiday Special",
        4: "Franchise Prequel",
        5: "Hummels & Heroin",
        6: "Sons a Witches",
        7: "Doubling Down",
        8: "Moss Piglets",
        9: "Super Hard PCness",
        10: "Splatty Tomato"
    },
    22: {
        1: "Dead Kids",
        2: "A Boy and a Priest",
        3: "The Problem with a Poo",
        4: "Tegridy Farms",
        5: "The Scoots",
        6: "Time to Get Cereal",
        7: "Nobody Got Cereal?",
        8: "Buddha Box",
        9: "Unfulfilled",
        10: "Bike Parade"
    },
    23: {
        1: "Mexican Joker",
        2: "Band in China",
        3: "Shots!!!",
        4: "Let Them Eat Goo",
        5: "Tegridy Farms Halloween Special",
        6: "Season Finale",
        7: "Board Girls",
        8: "Turd Burglars",
        9: "Basic Cable",
        10: "Christmas Snow"
    },
    24: {
        1: "The Pandemic Special",
        2: "South ParQ Vaccination Special",
        3: "South Park: Post Covid",
        4: "South Park: Post Covid: The Return of Covid"
    },
    25: {
        1: "Pajama Day",
        2: "The Big Fix",
        3: "City People",
        4: "Back to the Cold War",
        5: "Help, My Teenager Hates Me!",
        6: "Credigree Weed St. Patrick's Day Special",
        7: "South Park The Streaming Wars",
        8: "South Park The Streaming Wars Part 2"
    }
 }
