seasons = {
    1: {
        1: "Cartman Gets an Anal Probe",
        2: "Weight Gain 4000",
        3: "Volcano",
        4: "Big Gay Al's Big Gay Boat Ride",
        5: "An Elephant Makes Love to a Pig",
        6: "Death",
        7: "Pinkeye",
        8: "Starvin' Marvin",
        9: "Mr. Hankey, the Christmas Poo",
        10: "Damien",
        11: "Tom's Rhinoplasty",
        12: "Mecha-Streisand",
        13: "Cartman's Mom Is a Dirty Slut"
    },
    2: {
        1: "Terrance and Phillip in Not Without My Anus",
        2: "Cartman's Mom Is Still a Dirty Slut",
        3: "Ike's Wee Wee",
        4: "Chickenlover",
        5: "Conjoined Fetus Lady",
        6: "The Mexican Staring Frog of Southern Sri Lanka",
        7: "City on the Edge of Forever Flashbacks",
        8: "Summer Sucks",
        9: "Chef's Chocolate Salty Balls",
        10: "Chickenpox",
        11: "Roger Ebert Should Lay Off the Fatty Foods",
        12: "Clubhouses",
        13: "Cow Days",
        14: "Chef Aid",
        15: "Spookyfish",
        16: "Merry Christmas, Charlie Manson!",
        17: "Gnomes",
        18: "Prehistoric Ice Man"
    },
    3: {
        1: "Rainforest Shmainforest",
        2: "Spontaneous Combustion",
        3: "Succubus",
        4: "Jakovasaurs",
        5: "Tweek vs. Craig",
        6: "Sexual Harassment Panda",
        7: "Cat Orgy",
        8: "Two Guys Naked in a Hot Tub",
        9: "Jewbilee",
        10: "Korn's Groovy Pirate Ghost Mystery",
        11: "Chinpokomon",
        12: "Hooked on Monkey Fonics",
        13: "Starvin' Marvin in Space",
        14: "The Red Badge of Gayness",
        15: "Mr. Hankey's Christmas Classics",
        16: "Are You There God? It's Me, Jesus",
        17: "World Wide Recorder Concert"
    },
    4: {
        1: "The Tooth Fairy's Tats 2000",
        2: "Cartman's Silly Hate Crime 2000",
        3: "Timmy 2000",
        4: "Quintuplets 2000",
        5: "Cartman Joins NAMBLA",
        6: "Cherokee Hair Tampons",
        7: "Chef Goes Nanners",
        8: "Something You Can Do with Your Finger",
        9: "Do the Handicapped Go to Hell?",
        10: "Probably",
        11: "4th Grade",
        12: "Trapper Keeper",
        13: "Helen Keller! The Musical",
        14: '"Pip"Great Expectations',
        15: "Fat Camp",
        16: "The Wacky Molestation Adventure",
        17: "A Very Crappy Christmas"
    },
    5: {
        1: "It Hits the Fan",
        2: "Cripple Fight",
        3: "Super Best Friends",
        4: "Scott Tenorman Must Die",
        5: "Terrance and Phillip: Behind the Blow",
        6: "Cartmanland",
        7: "Proper Condom Use",
        8: "Towelie",
        9: "Osama bin Laden Has Farty Pants",
        10: "How to Eat with Your Butt",
        11: "The Entity",
        12: "Here Comes the Neighborhood",
        13: "Kenny Dies",
        14: "Butters' Very Own Episode"
    },
    6: {
        1: "Jared Has Aides",
        2: "Asspen",
        3: "Freak Strike",
        4: "Fun with Veal",
        5: "The New Terrance and Phillip Movie Trailer",
        6: "Professor Chaos",
        7: "Simpsons Already Did It",
        8: "Red Hot Catholic Love",
        9: "Free Hat",
        10: "Bebe's Boobs Destroy Society",
        11: "Child Abduction Is Not Funny",
        12: "A Ladder to Heaven",
        13: "The Return of the Fellowship of the Ring to the Two Towers",
        14: "The Death Camp of Tolerance",
        15: "The Biggest Douche in the Universe",
        16: "My Future Self 'n' Me",
        17: "Red Sleigh Down"
    },
    7: {
        1: "Cancelled",
        2: "Krazy Kripples",
        3: "Toilet Paper",
        4: "I'm a Little Bit Country",
        5: "Fat Butt and Pancake Head",
        6: "Lil' Crime Stoppers",
        7: "Red Man's Greed",
        8: "South Park Is Gay",
        9: "Christian Rock Hard",
        10: "Grey Dawn",
        11: "Casa Bonita",
        12: "All About Mormons",
        13: "Butt Out",
        14: "Raisins",
        15: "It's Christmas in Canada"
    },
    8: {
        1: "Good Times with Weapons",
        2: "Up the Down Steroid",
        3: "The Passion of the Jew",
        4: "You Got F'd in the A",
        5: "Awesom-O",
        6: "The Jeffersons",
        7: "Goobacks",
        8: "Douche and Turd",
        9: "Something Wall-Mart This Way Comes",
        10: "Pre-School",
        11: "Quest for Ratings",
        12: "Stupid Spoiled Whore Video Playset",
        13: "Cartman's Incredible Gift",
        14: "Woodland Critter Christmas"
    },
    9: {
        1: "Mr. Garrison's Fancy New Vagina",
        2: "Die Hippie, Die",
        3: "Wing",
        4: "Best Friends Forever",
        5: "The Losing Edge",
        6: "The Death of Eric Cartman",
        7: "Erection Day",
        8: "Two Days Before the Day After Tomorrow",
        9: "Marjorine",
        10: "Follow That Egg!",
        11: "Ginger Kids",
        12: "Trapped in the Closet",
        13: "Free Willzyx",
        14: "Bloody Mary"
    },
    10: {
        1: "The Return of Chef",
        2: "Smug Alert!",
        3: "Cartoon Wars Part I",
        4: "Cartoon Wars Part II",
        5: "A Million Little Fibers",
        6: "ManBearPig",
        7: "Tsst",
        8: "Make Love, Not Warcraft",
        9: "Mystery of the Urinal Deuce",
        10: "Miss Teacher Bangs a Boy",
        11: "Hell on Earth 2006",
        12: "Go God Go",
        13: "Go God Go XII",
        14: "Stanley's Cup"
    },
    11: {
        1: "With Apologies to Jesse Jackson",
        2: "Cartman Sucks",
        3: "Lice Capades",
        4: "The Snuke",
        5: "Fantastic Easter Special",
        6: "D-Yikes!",
        7: "Night of the Living Homeless",
        8: "Le Petit Tourette",
        9: "More Crap",
        10: "Imaginationland Episode I",
        11: "Imaginationland Episode II",
        12: "Imaginationland Episode III",
        13: "Guitar Queer-O",
        14: "The List"
    },
    12: {
        1: "Tonsil Trouble",
        2: "Britney's New Look",
        3: "Major Boobage",
        4: "Canada on Strike",
        5: "Eek, a Penis!",
        6: "Over Logging",
        7: "Super Fun Time",
        8: "The China Probrem",

    }
 }
